name: netguru_values_generator
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  get_it: ^7.2.0
  dartz: ^0.10.0
  mockito: ^5.0.15
  equatable: ^2.0.3
  freezed: ^0.14.2
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null

flutter:

  fonts:
    - family: Josefin-Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Italic.ttf
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf

  uses-material-design: true
